Disable "View PDF" button when schedule page returns no results
ynorth-projects/openy_repeat pull request #25
Opened 2022-10-19 12:39 UTC by andreyzb

2022-10-19 14:23 UTC, andreyzb commented
@podarok Please review

2022-10-20 07:20 UTC, podarok requested changes

2022-10-20 07:20 UTC, podarok commented on js/repeat/src/repeat.js
> +        //$('#datepicker').datepicker("setDate", moment(component.date).format('YYYY-MM-DD'));
let's avoid commented code

2022-10-20 07:20 UTC, podarok commented on js/repeat/src/repeat.js
> +        // In case if we use unselect date.
```suggestion
        // In case we use unselect date.
```

2022-10-20 07:29 UTC, andreyzb commented
@podarok I did not rebuild repeat.js because feedback changes did not touch any logic

2022-10-20 11:19 UTC, merged

2022-10-20 11:20 UTC, podarok commented
Tagged https://github.com/ynorth-projects/openy_repeat/releases/tag/2.0.11