feat: codesniffer and rector fixes for Drupal 10
ynorth-projects/openy_repeat pull request #29
Opened 2023-05-03 12:52 UTC by podarok

Addresses: https://github.com/YCloudYUSA/yusaopeny/pull/8
Fixes: https://yusa.atlassian.net/browse/DS-64

2023-05-03 13:52 UTC, svicervlad requested changes

2023-05-03 13:52 UTC, svicervlad commented on src/OpenyRepeatRepository.php
> +   *
Description required

2023-05-03 13:52 UTC, svicervlad commented on src/OpenyRepeatRepository.php
> +   *
Description required

2023-05-04 07:28 UTC, podarok commented on src/OpenyRepeatRepository.php
> +   *
```suggestion
   * Obtains sessions from the PEF storage.
```

2023-05-04 07:32 UTC, merged