feature/add-filter-by-instructor|Added the filter by instructor for t…
ynorth-projects/openy_repeat pull request #47
Opened 2024-04-23 10:34 UTC by oleh-rymar

…he Repeat Schedules block.

2024-04-23 15:30 UTC, froboy requested changes
@oleh-rymar this looks good. I left a few small comments. Could you please add test steps and some screenshots of the expected results when the module is enabled?

2024-04-23 15:30 UTC, froboy commented on templates/openy-repeat-schedule-dashboard--sidebar.html.twig
> +        {# inscructor name select list #}
```suggestion
        {# instructor name select list #}
```

2024-04-23 15:30 UTC, froboy commented on modules/repeat_schedules_instructor/config/install/field.storage.paragraph.field_prgf_repeat_schedule_filt.yml
> +      value: inscructorname
```suggestion
      value: instructorname
```

2024-04-23 15:30 UTC, froboy commented on templates/openy-repeat-schedule-dashboard--sidebar.html.twig
> +        {% if filters.inscructorname %}
```suggestion
        {% if filters.instructorname %}
```

2024-04-23 17:30 UTC, oleh-rymar commented
@froboy 
Fixed. Please, check.

2024-04-24 13:29 UTC, froboy approved these changes
Looks great. Thanks for the responses!

2024-04-25 07:35 UTC, podarok commented
I think height of the element in Dropdown is not correct
We need to do better UX

![image](https://github.com/ynorth-projects/openy_repeat/assets/563412/8d23e658-0b37-4b7a-a4f7-7536291d3085)

2024-04-25 08:28 UTC, oleh-rymar commented
![Screenshot from 2024-04-25 10-16-46](https://github.com/ynorth-projects/openy_repeat/assets/164229587/60381f1d-96f3-4ef5-9acc-b57b424486f7)
@podarok @froboy 
Updated.

2024-04-25 16:22 UTC, podarok commented
See https://yusaslackinstance.slack.com/archives/C03E6SQQ0Q5/p1714061856384559?thread_ts=1713557003.572269&cid=C03E6SQQ0Q5 @oleh-rymar 

I'm merging this as it is functional
BUt if we can do select list as dropdown menu from https://www.w3schools.com/css/css_dropdowns.asp - that would be great

2024-04-25 16:22 UTC, merged